array[0] = obj_item_sonic;
array[1] = obj_item_snail;
array[2] = obj_item_convert;
array[3] = obj_item_abilityplus;
array[4] = obj_item_shrink;
itemNum = random(array_length_1d(array)) - 1;
obj_item_controller.itemsOnField++;
var itemX = irandom_range(100, room_width-100);
var itemY = irandom_range(700, 800);
instance_create(itemX, itemY, array[itemNum]);
